development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: Youdong
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: Youdong
  password:
  host: localhost